//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModules.WcfDataService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfDataService.IServerStatus")]
    public interface IServerStatus {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerStatus/GetServerStatusDetails", ReplyAction="http://tempuri.org/IServerStatus/GetServerStatusDetailsResponse")]
        System.Data.DataTable GetServerStatusDetails();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerStatus/GetServerStatusDetails", ReplyAction="http://tempuri.org/IServerStatus/GetServerStatusDetailsResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetServerStatusDetailsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServerStatusChannel : DataModules.WcfDataService.IServerStatus, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServerStatusClient : System.ServiceModel.ClientBase<DataModules.WcfDataService.IServerStatus>, DataModules.WcfDataService.IServerStatus {
        
        public ServerStatusClient() {
        }
        
        public ServerStatusClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServerStatusClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServerStatusClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServerStatusClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable GetServerStatusDetails() {
            return base.Channel.GetServerStatusDetails();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetServerStatusDetailsAsync() {
            return base.Channel.GetServerStatusDetailsAsync();
        }
    }
}
